### ISSUE TITLE
Excel file: empty columns

### ISSUE THREAD

**Issue by yolile** [open-contracting/spoonbill-web#208] opened 2021-05-19 20:46 UTC
Tested with https://ocp12.open-contracting.org/#/download?url=f90d1d20-7903-431c-b53c-f5c78a54e9fc&selections=bf18a7e0-a1c9-4257-9a9e-e8263819ba21

original  data https://www.contrataciones.gov.py/datos/api/v3/doc/ocds/releases/id/394282-adquisicion-cubiertas-maquinarias-vehiculos-utilitarios-annp-1-1621414358

- All the columns in the documents sheet are empty, (besides: ocid, id, rowID, parentID)
- Most of the columns in the tenders sheets are empty, including core fields as tender/value/amount and tender/value/currency, and core arrays as tender/items and all its fields 
- The planning/items and planning/budgetBreakdown array columns are empty

Note that in the "Edit tables" section, the preview shows the correct and complete data:

![image](https://user-images.githubusercontent.com/6834122/118882006-ae747a00-b8c1-11eb-898f-140ec436b07d.png)

**Comment by sorenabell** [comment] 2021-09-30 10:16
The issue is related https://github.com/open-contracting/spoonbill/issues/67.


_The planning/items and planning/budgetBreakdown array columns are empty_  - fixed

**Comment by jpmckinney** [comment] 2021-12-15 20:56
Closing in favor of https://github.com/open-contracting/spoonbill/issues/67

**Closed by jpmckinney** 2021-12-15 20:56 UTC
Labels: bug
